import type { Development, DevelopmentFloorPlan } from "@/types/development";
import type { JournalArticle } from "@/types/journal";
import type { Developer } from "@/types/developer";

export const mockDevelopers: Developer[] = [
  {
    id: "dev-1",
    slug: "bensons-property-group",
    name: "Bensons Property Group",
    description:
      "Melbourne-based developer with a 30-year history and 100% project completion rate. Specialists in luxury high-rise residential across Queensland and Victoria.",
    logo_url: null,
    website: "https://bensons.com.au",
    abn: null,
    state: "QLD",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 3,
  },
  {
    id: "dev-2",
    slug: "gardner-vaughan-group",
    name: "Gardner Vaughan Group",
    description:
      "Family-owned Queensland developer with 25+ years building quality residential communities across South East Queensland.",
    logo_url: null,
    website: null,
    abn: null,
    state: "QLD",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 2,
  },
  {
    id: "dev-3",
    slug: "edge-visionary-living",
    name: "Edge Visionary Living",
    description:
      "Perth-based developer redefining apartment living in Western Australia with resort-style amenities and innovative design.",
    logo_url: null,
    website: null,
    abn: null,
    state: "WA",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 2,
  },
  {
    id: "dev-4",
    slug: "miura-group",
    name: "Miura Group",
    description:
      "Boutique Melbourne developer delivering flagship residential projects that respond sensitively to their local context and heritage.",
    logo_url: null,
    website: null,
    abn: null,
    state: "VIC",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 1,
  },
  {
    id: "dev-5",
    slug: "celsius-property-group",
    name: "Celsius Property Group",
    description:
      "Boutique Western Australian developer focused on delivering architecturally considered apartments in sought-after inner-city locations.",
    logo_url: null,
    website: null,
    abn: null,
    state: "WA",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 1,
  },
  {
    id: "dev-6",
    slug: "little-projects",
    name: "Little Projects",
    description:
      "Innovative developer known for luxury lifestyle-driven developments across Queensland's premier coastal and urban locations.",
    logo_url: null,
    website: null,
    abn: null,
    state: "QLD",
    is_published: true,
    created_at: "2026-01-01T00:00:00.000Z",
    development_count: 1,
  },
];

export const mockDevelopments: Development[] = [
  {
    id: "d1",
    slug: "chevron-one",
    name: "Chevron One",
    suburb: "Chevron Island",
    state: "QLD",
    price_from: 106700000,
    price_display: "$1.067M",
    beds_min: 2,
    beds_max: 3,
    completion_quarter: "Mid 2025",
    type: "Apartments",
    developer_id: "dev-1",
    tag: "Featured",
    status: "Selling now",
    summary:
      "An iconic landmark rising 41 levels above Chevron Island, maximising space and natural light with breathtaking panoramic views of the ocean, Nerang River and Gold Coast hinterland. Architecturally inspired by the natural shapes and textures of the coastline.",
    lifestyle: ["Ocean views", "River views", "Concierge", "Resort pool"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: 41,
    residence_count: null,
    lat: -28.0023,
    lng: 153.4145,
    is_published: true,
    is_featured: true,
    hero_image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&q=80",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-04-01T00:00:00.000Z",
    developer: mockDevelopers[0],
  },
  {
    id: "d2",
    slug: "signature-broadbeach",
    name: "Signature Broadbeach",
    suburb: "Broadbeach",
    state: "QLD",
    price_from: 61500000,
    price_display: "$615K",
    beds_min: 1,
    beds_max: 3,
    completion_quarter: null,
    type: "Apartments",
    developer_id: "dev-6",
    tag: "New launch",
    status: "Selling now",
    summary:
      "Luxury beachside living half a block from Kurrawa patrolled beach. Features the Gold Coast's first Olympic-sized 50m infinity edge pool spanning the entire podium level, alongside a gym, steam room, sauna, spa, outdoor lawn, BBQ, teppanyaki grill and private dining room.",
    lifestyle: ["Beachside", "Infinity pool", "Walk to beach", "Near dining precinct"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: null,
    residence_count: null,
    lat: -28.0267,
    lng: 153.4317,
    is_published: true,
    is_featured: true,
    hero_image_url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1600&q=80",
    created_at: "2026-01-02T00:00:00.000Z",
    updated_at: "2026-04-02T00:00:00.000Z",
    developer: mockDevelopers[5],
  },
  {
    id: "d3",
    slug: "estilo-on-the-park",
    name: "Estilo on the Park",
    suburb: "Chermside",
    state: "QLD",
    price_from: 37900000,
    price_display: "$379K",
    beds_min: 1,
    beds_max: 4,
    completion_quarter: null,
    type: "Apartments",
    developer_id: "dev-2",
    tag: "Editor's pick",
    status: "Selling now",
    summary:
      "An exclusive address on the very last park-side location in Chermside. Nestled on the edge of Seventh Brigade Park, moments from Westfield Chermside. A contemporary facade with a Spanish twist — the arches adopt a reference to the Spanish essence of 'Estilo'. The perfect blend of tranquillity, convenience and contemporary living.",
    lifestyle: ["Park views", "Walk to Westfield", "Spanish architecture", "Village lifestyle"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: null,
    residence_count: 51,
    lat: -27.3893,
    lng: 153.0317,
    is_published: true,
    is_featured: false,
    hero_image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    created_at: "2026-01-03T00:00:00.000Z",
    updated_at: "2026-04-03T00:00:00.000Z",
    developer: mockDevelopers[1],
  },
  {
    id: "d4",
    slug: "silk-one",
    name: "Silk One",
    suburb: "Woolloongabba",
    state: "QLD",
    price_from: 37800000,
    price_display: "$378K",
    beds_min: 1,
    beds_max: 2,
    completion_quarter: null,
    type: "Apartments",
    developer_id: "dev-2",
    tag: "Trending",
    status: "Selling now",
    summary:
      "169 contemporary apartments adjacent to The Gabba sporting ground in Woolloongabba — one of Brisbane's most rapidly evolving inner-city precincts. A range of one and two bedroom configurations with exceptional access to public transport, dining and entertainment.",
    lifestyle: ["Inner Brisbane", "Near The Gabba", "Transport hub", "Investment grade"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: 22,
    residence_count: 169,
    lat: -27.4869,
    lng: 153.0336,
    is_published: true,
    is_featured: false,
    hero_image_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600&q=80",
    created_at: "2026-01-04T00:00:00.000Z",
    updated_at: "2026-04-04T00:00:00.000Z",
    developer: mockDevelopers[1],
  },
  {
    id: "d5",
    slug: "eden-floreat",
    name: "Eden Floreat",
    suburb: "Floreat",
    state: "WA",
    price_from: 289500000,
    price_display: "From $POA",
    beds_min: 1,
    beds_max: 3,
    completion_quarter: "Completed",
    type: "Apartments",
    developer_id: "dev-3",
    tag: "Featured",
    status: "Selling now",
    summary:
      "163 residences set on the edge of Perry Lakes, 3km from City Beach and 7km from the Perth CBD. Over 1,800sqm of resort-style amenities including a heated 25m pool, gymnasium, yoga studio, steam room, sauna, private dining rooms and wine cellar. Views across Perry Lakes to the Indian Ocean.",
    lifestyle: ["Lake views", "25m heated pool", "Yoga studio", "Walk to City Beach"],
    architect: "Hillam Architects",
    interiors: null,
    landscape: null,
    builder: null,
    levels: null,
    residence_count: 163,
    lat: -31.9271,
    lng: 115.8005,
    is_published: true,
    is_featured: true,
    hero_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=80",
    created_at: "2026-01-05T00:00:00.000Z",
    updated_at: "2026-04-05T00:00:00.000Z",
    developer: mockDevelopers[2],
  },
  {
    id: "d6",
    slug: "elysian-subiaco",
    name: "Elysian Subiaco",
    suburb: "Subiaco",
    state: "WA",
    price_from: null,
    price_display: null,
    beds_min: null,
    beds_max: null,
    completion_quarter: "Completed 2024",
    type: "Apartments",
    developer_id: "dev-5",
    tag: "Editor's pick",
    status: "Final release",
    summary:
      "37 elegant homes at the Paris end of Subiaco. Grand arches and vertical ribbed details draw inspiration from Subiaco's historic architectural character. Nestled beside Kings Park, surrounded by tree-lined streets, boutique shopping, gourmet Farmers Markets and cafes.",
    lifestyle: ["Near Kings Park", "Boutique village", "Heritage architecture", "Farmers Markets"],
    architect: "MJA Studio",
    interiors: null,
    landscape: null,
    builder: null,
    levels: 6,
    residence_count: 37,
    lat: -31.9479,
    lng: 115.8269,
    is_published: true,
    is_featured: false,
    hero_image_url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=80",
    created_at: "2026-01-06T00:00:00.000Z",
    updated_at: "2026-04-06T00:00:00.000Z",
    developer: mockDevelopers[4],
  },
  {
    id: "d7",
    slug: "12-montgomery",
    name: "12 Montgomery",
    suburb: "Doncaster East",
    state: "VIC",
    price_from: 93500000,
    price_display: "$935K",
    beds_min: 2,
    beds_max: 4,
    completion_quarter: null,
    type: "Townhouses",
    developer_id: "dev-4",
    tag: "New launch",
    status: "Register interest",
    summary:
      "Six architecturally designed townhouses located on a leafy street in Doncaster East, surrounded by diverse amenity and every convenience within walking distance. Only 18km from Melbourne CBD with access to major shopping precincts, arterial roads and Eastlink Freeway.",
    lifestyle: ["Leafy streets", "18km to CBD", "Near Eastlink", "School zones"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: null,
    residence_count: 6,
    lat: -37.7831,
    lng: 145.1383,
    is_published: true,
    is_featured: false,
    hero_image_url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1600&q=80",
    created_at: "2026-01-07T00:00:00.000Z",
    updated_at: "2026-04-07T00:00:00.000Z",
    developer: mockDevelopers[3],
  },
  {
    id: "d8",
    slug: "auborn-lane",
    name: "Auborn Lane",
    suburb: "Hawthorn",
    state: "VIC",
    price_from: null,
    price_display: null,
    beds_min: null,
    beds_max: null,
    completion_quarter: null,
    type: "Apartments",
    developer_id: "dev-4",
    tag: "Editor's pick",
    status: "Register interest",
    summary:
      "The flagship Miura development. A boutique collection of 20 residences — including a full-floor penthouse and three levels of half-floor sub-penthouses — inspired by Hawthorn's heritage architecture. Gaggenau-appointed, generously proportioned, and sensitively conceived for the location's buoyant village lifestyle.",
    lifestyle: ["Heritage location", "Village lifestyle", "Boutique", "Penthouse collection"],
    architect: null,
    interiors: null,
    landscape: null,
    builder: null,
    levels: null,
    residence_count: 20,
    lat: -37.8224,
    lng: 145.0339,
    is_published: true,
    is_featured: false,
    hero_image_url: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1600&q=80",
    created_at: "2026-01-08T00:00:00.000Z",
    updated_at: "2026-04-08T00:00:00.000Z",
    developer: mockDevelopers[3],
  },
];

export const mockJournalArticles: JournalArticle[] = [
  {
    id: "j1",
    slug: "5-reasons-buying-off-the-plan-is-a-great-investment",
    title: "5 Reasons Buying Off the Plan Is a Great Investment",
    category: "Market",
    hero_image_url: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&q=80",
    body_html:
      "<p>Buying off the plan has long been favoured by savvy Australian investors — and for good reason. When you commit to a property before it's built, you lock in today's price for tomorrow's asset.</p><p>Here are five compelling reasons why off-the-plan continues to attract buyers across every Australian capital city.</p><h2>1. Stamp Duty Savings</h2><p>In most states, buying off the plan entitles you to significant stamp duty concessions — sometimes eliminating the cost entirely for owner-occupiers. This alone can save tens of thousands of dollars.</p><h2>2. Capital Growth During Construction</h2><p>With settlements typically 12–36 months away, buyers who purchase early often find the market value of their property has grown by the time they settle — creating immediate equity.</p><h2>3. Depreciation Benefits for Investors</h2><p>New properties attract higher depreciation deductions than established ones. A quantity surveyor report on a new development can unlock significant annual tax benefits.</p><h2>4. Lower Maintenance Costs</h2><p>Everything is new. Appliances, fixtures, and structure all carry warranties — reducing maintenance costs in the critical first years of ownership.</p><h2>5. Choice of Apartment</h2><p>Buying early means the best apartments — corner positions, higher floors, park-facing aspects — are still available. Late buyers get what's left.</p>",
    author: "The Editors",
    read_time_minutes: 6,
    published_at: "2026-04-28T09:00:00.000Z",
    is_published: true,
    created_at: "2026-04-28T09:00:00.000Z",
  },
  {
    id: "j2",
    slug: "what-to-look-for-when-buying-off-the-plan",
    title: "What to Look For When Buying Off the Plan",
    category: "Guide",
    hero_image_url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80",
    body_html:
      "<p>Not all off-the-plan developments are created equal. Before you sign a contract, there are several key factors that distinguish a sound investment from a costly mistake.</p><h2>Developer Track Record</h2><p>Research completed projects. Have they delivered on time? Does the finished product match the renders? A developer with a 100% completion rate and satisfied buyers is a fundamentally different proposition from one with incomplete projects or litigation history.</p><h2>Location Fundamentals</h2><p>No amount of specification can compensate for a poor location. Look for proximity to employment hubs, public transport, lifestyle amenity, and schools. The suburb's long-term supply pipeline matters too — excess stock suppresses both rental yields and resale values.</p><h2>Contract Sunset Clauses</h2><p>Every off-the-plan contract contains a sunset clause — a date by which the developer must complete the project, or either party can rescind. Understand the clause length and the developer's right to extend it before signing.</p><h2>Specification Quality</h2><p>Renders flatter. Ask for a detailed finishes schedule — the specific brands, materials, and configurations that will be delivered. Substitution clauses in contracts can allow downgrades at settlement.</p>",
    author: "The Editors",
    read_time_minutes: 8,
    published_at: "2026-04-21T09:00:00.000Z",
    is_published: true,
    created_at: "2026-04-21T09:00:00.000Z",
  },
  {
    id: "j3",
    slug: "why-townhouse-living-is-booming-in-australia",
    title: "Why Townhouse Living Is Booming in Australia",
    category: "Editorial",
    hero_image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    body_html:
      "<p>Australia's townhouse market is experiencing a structural shift. As apartment supply in inner-city precincts continues to build, buyers seeking more space — without the maintenance burden of a freestanding house — are driving unprecedented demand for the townhouse format.</p><p>The appeal is straightforward: ground-floor living, private outdoor space, double garages, and separation between living and sleeping areas that a typical apartment cannot replicate. For families, the townhouse offers a genuine alternative to established housing at a price point that remains accessible.</p><p>Developers have responded. Where townhouse projects were once boutique by necessity, we're now seeing medium-density townhouse communities of 30–100 dwellings that offer shared amenity, landscaped gardens, and communal spaces previously associated only with apartment towers.</p><p>The suburbs benefiting most are those within 15–25km of the CBD — the middle ring that offers land value upside, established infrastructure, and the lifestyle attributes that attract long-term owner-occupiers.</p>",
    author: "James Whitfield",
    read_time_minutes: 5,
    published_at: "2026-04-14T09:00:00.000Z",
    is_published: true,
    created_at: "2026-04-14T09:00:00.000Z",
  },
  {
    id: "j4",
    slug: "breaking-down-australian-off-the-plan-property-categories",
    title: "Breaking Down Australian Off-the-Plan Property Categories",
    category: "Guide",
    hero_image_url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80",
    body_html:
      "<p>Buying off the plan can be one of the smartest ways to secure a property — with options ranging from sleek new apartments to spacious house and land packages, each offering unique benefits suited to different buyer profiles. Understanding the categories is the first step toward choosing the property that fits your lifestyle and investment goals.</p><h2>Apartments</h2><p>The most common off-the-plan purchase. Apartments range from compact studio configurations in urban centres to full-floor penthouses in prestige towers. Key variables: building quality, amenity offering, floor level, aspect, and car parking.</p><h2>Townhouses</h2><p>Multi-level attached dwellings with private outdoor space and, typically, a garage. Popular with families and downsizers alike. Usually within medium-density precincts rather than individual developments.</p><h2>House & Land Packages</h2><p>A builder-provided house design on a titled lot within a land estate. Buyers select from a range of façades and floor plans. Common in outer suburban growth corridors. Attractive to first home buyers accessing government grants.</p><h2>Land Estates</h2><p>Residential subdivisions where buyers purchase a titled lot and engage their own builder. Maximum flexibility; longer lead time. Popular in regional and outer-suburban markets.</p>",
    author: "The Editors",
    read_time_minutes: 7,
    published_at: "2026-04-07T09:00:00.000Z",
    is_published: true,
    created_at: "2026-04-07T09:00:00.000Z",
  },
];

export const mockFloorPlans: DevelopmentFloorPlan[] = [
  {
    id: "fp1",
    development_id: "d1",
    plan_type: "Type 01",
    config: "2 bed, 2 bath",
    internal_sqm: 85,
    price_from: 106700000,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    id: "fp2",
    development_id: "d1",
    plan_type: "Type 02",
    config: "2 bed, 2 bath + study",
    internal_sqm: 102,
    price_from: 145000000,
    image_url: "https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=600&q=80",
  },
  {
    id: "fp3",
    development_id: "d1",
    plan_type: "Type 03",
    config: "3 bed, 2 bath",
    internal_sqm: 138,
    price_from: 198000000,
    image_url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80",
  },
  {
    id: "fp4",
    development_id: "d1",
    plan_type: "Type 04 — Sub-Penthouse",
    config: "3 bed, 3 bath",
    internal_sqm: 198,
    price_from: 265800000,
    image_url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80",
  },
];
